name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

#      - name: Setup Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: 16.x
#          cache: 'npm'
#
#      - name: Npm install
#        run: npm ci

      # tar -cvf jenkins_backup.tar ./jenkins_backup
      # split -b 90m -d jenkins_backup.tar jenkins_backup

#      - name: Prepare Jenkins data
#        run: |
#          cat ${{ github.workspace }}/jenkins_data/jenkins_backup0* > ${{ github.workspace }}/jenkins_backup.tar
#          md5sum ${{ github.workspace }}/jenkins_backup.tar
#
#      - name: Extract Jenkins data and set permission
#        run: |
#          tar -xvf ./jenkins_backup.tar
#          chmod -R 777 ./jenkins_backup/var/jenkins_home
#
#      - name: Docker login
#        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
#
#      - name: Docker start
#        run: docker run --rm --detach -p 8080:8080 -p 50000:50000 -v ${{ github.workspace }}/jenkins_backup/var/jenkins_home:/var/jenkins_home jenkins/jenkins:2.492.2-lts-jdk17
#
#      - name: Wait for the Jenkins
#        run: ./.github/wait-for-jenkins.sh
